### ISSUE TITLE
bitcore.deps.Buffer reverse() issue in safari browser

### ISSUE THREAD

**Issue by RCasatta** [bitpay/bitcore#1414]
As stated in the subject, the reverse function on the Buffer implementation is not working on safari browser version 9.1.1 (11601.6.17) on Mac OS x 10.11.5 (15F34)

Here is the testing code

```
>> var a=bitcore.deps.Buffer("ab")
<Buffer 61 62>
>> a.reverse()
TypeError: a.reverse is not a function. (In 'a.reverse()', 'a.reverse' is undefined)
```

**Comment by braydonf** [comment]
Since Node.js 0.10 and 0.12 are supported, there is:
```
var buf2 = bitcore.util.buffer.reverse(buf)
```
We should update the implementation to use buffer.reverse if it's available.

**Comment by braydonf** [comment]
Took a look to see if there would be some performance benefits by running  [benchmark/serialization.js](https://github.com/bitpay/bitcore-lib/blob/master/benchmark/serialization.js):

Without `buffer.reverse()`
```
bufferReader.readReverse() x 1,971,988 ops/sec ±0.25% (384 runs sampled)
```

Using `buffer.reverse()`
```
bufferReader.readReverse() x 2,518,390 ops/sec ±0.22% (383 runs sampled)
```

It doesn't look buffer.reverse is documented at https://nodejs.org/api/buffer.html, however it modifies the original buffer, so a copy needs to be made since many times the original is left intact.


Using `buffer.reverse()` with a copy.
```
bufferReader.readReverse() x 1,414,281 ops/sec ±0.34% (380 runs sampled)
```

Looks like the current implementation is the fastest still for how it's being used.
